version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directories:
      - /
      - /python
    schedule:
      interval: daily
    groups:
      dev-dependencies:
        dependency-type: development
    versioning-strategy: increase
