sync_changes_to_github:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "kudoai/chat-prompts"
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://gitlab.com/kudoai/chat-prompts.git
    - git push --force -o ci.skip https://$GITHUB_SYNC_PAT@github.com/KudoAI/chat-prompts.git HEAD:main
