name: Lint pushes + PRs
on: [push, pull_request]

jobs:
  lint-all:
    name: Lint all files
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.x

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Lint all files
        run: nox -s lint-all
